FROM mcr.microsoft.com/vscode/devcontainers/base:ubuntu

RUN sudo apt update && \
    sudo apt install -y \
        autoconf \
        automake \
        build-essential \
        cmake \
        libtool \
        pkg-config \
        nasm \
        zlib1g-dev \
        libvorbis-dev \
        libx264-dev \
        libx265-dev \
        libxml2-dev \
        python3-pip \
        python3-virtualenv
