from av.logging import get_last_error

classes: dict[int, Exception]

def code_to_tag(code: int) -> bytes: ...
def tag_to_code(tag: bytes) -> int: ...
def make_error(res: int, filename=None, log=None): ...

class FFmpegError(Exception):
    def __init__(self, code: int, message, filename=None, log=None): ...

class LookupError(FFmpegError): ...
class HTTPError(FFmpegError): ...
class HTTPClientError(FFmpegError): ...
class UndefinedError(FFmpegError): ...
class InvalidDataError(ValueError): ...
