from typing import Iterator, overload

from av.indexentry import IndexEntry

class FrameIndex:
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[IndexEntry]: ...
    @overload
    def __getitem__(self, index: int) -> IndexEntry | None: ...
    @overload
    def __getitem__(self, index: slice) -> list[IndexEntry | None]: ...
    def search_timestamp(
        self, timestamp, *, backward: bool = True, any_frame: bool = False
    ) -> int: ...
