#!/bin/bash

# Exit as soon as something errors.
set -e

if [[ ! "$PYAV_ACTIVATED" ]]; then
    export here="$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)"
    source "$here/activate.sh"
fi
cd "$PYAV_ROOT"


exec "$PYAV_PYTHON" setup.py config build_ext --inplace

