#!/bin/sh

set -xe

if [ -z "$1" ]; then
    echo "Usage: $0 <prefix>"
    exit 1
fi

destdir=$1
ffmpeg_version=4.2.2

builddir=`pwd`/build
sourcedir=`pwd`/source

for d in $builddir $destdir; do
    if [ -e $d ]; then
        rm -rf $d
    fi
done

build() {
    path=$builddir/$1
    shift
    configure_args=$*
    cd $path
    ./configure $configure_args --prefix=$destdir
    make -j
    make install
    cd $builddir
}

extract() {
    path=$builddir/$1
    url=$2
    tarball=$sourcedir/`echo $url | sed -e 's/.*\///'`

    if [ ! -e $tarball ]; then
        curl -L -o $tarball $url
    fi

    mkdir $path
    tar xf $tarball -C $path --strip-components 1
}

if [ "`uname`" = "Linux" ]; then
    outputdir=/output
    outputfile=$outputdir/ffmpeg-$ffmpeg_version-manylinux_$(uname -m).tar.bz2
    x265_args=""
else
    outputdir=`pwd`/output
    outputfile=$outputdir/ffmpeg-$ffmpeg_version-macosx_$(uname -m).tar.bz2
    x265_args="-DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE"
fi

mkdir -p $outputdir
if [ ! -e $outputfile ]; then
    mkdir $builddir
    mkdir -p $sourcedir
    cd $builddir

    export LDFLAGS="-L$destdir/lib $LDFLAGS"
    export PATH=$destdir/bin:$PATH
    export PKG_CONFIG_PATH=$destdir/lib/pkgconfig

    # install nasm
    extract nasm https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/nasm-2.14.02.tar.bz2
    build nasm

    # build xz
    extract xz https://tukaani.org/xz/xz-5.2.5.tar.bz2
    build xz

    # build zlib
    extract zlib https://www.zlib.net/zlib-1.2.11.tar.gz
    build zlib

    # build xml2 (uses xz and zlib)
    extract xml2 ftp://xmlsoft.org/libxml2/libxml2-sources-2.9.10.tar.gz
    build xml2 --without-python

    # build lame
    extract lame http://deb.debian.org/debian/pool/main/l/lame/lame_3.100.orig.tar.gz
    sed -i.bak '/^lame_init_old$/d' lame/include/libmp3lame.sym
    build lame

    # build ogg
    extract ogg http://downloads.xiph.org/releases/ogg/libogg-1.3.4.tar.gz
    cat <<EOF | patch -p0
--- ogg/include/ogg/os_types.h
+++ ogg/include/ogg/os_types.h
@@ -72,11 +72,11 @@
 
 #  include <sys/types.h>
    typedef int16_t ogg_int16_t;
-   typedef uint16_t ogg_uint16_t;
+   typedef u_int16_t ogg_uint16_t;
    typedef int32_t ogg_int32_t;
-   typedef uint32_t ogg_uint32_t;
+   typedef u_int32_t ogg_uint32_t;
    typedef int64_t ogg_int64_t;
-   typedef uint64_t ogg_uint64_t;
+   typedef u_int64_t ogg_uint64_t;
 
 #elif defined(__HAIKU__)
 
EOF
    build ogg

    # build opencore-amr
    extract opencore-amr http://deb.debian.org/debian/pool/main/o/opencore-amr/opencore-amr_0.1.5.orig.tar.gz
    build opencore-amr

    # build openjpeg
    extract openjpeg https://github.com/uclouvain/openjpeg/archive/v2.3.1.tar.gz
    cd openjpeg
    cmake . -DCMAKE_INSTALL_PREFIX=$destdir
    make -j
    make install
    cd $builddir

    # build opus
    extract opus https://archive.mozilla.org/pub/opus/opus-1.3.1.tar.gz
    build opus

    # build speex
    extract speex http://downloads.xiph.org/releases/speex/speex-1.2.0.tar.gz
    build speex

    # build twolame
    extract twolame http://deb.debian.org/debian/pool/main/t/twolame/twolame_0.4.0.orig.tar.gz
    build twolame

    # build vorbis (requires ogg)
    extract vorbis http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.6.tar.gz
    build vorbis

    # build theora (requires vorbis)
    extract theora http://downloads.xiph.org/releases/theora/libtheora-1.1.1.tar.gz
    build theora --disable-examples

    # build x264
    extract x264 https://code.videolan.org/videolan/x264/-/archive/master/x264-master.tar.bz2
    build x264 --enable-shared

    # build x265
    extract x265 http://ftp.videolan.org/pub/videolan/x265/x265_3.2.1.tar.gz
    cd x265/build
    cmake ../source -DCMAKE_INSTALL_PREFIX=$destdir $x265_args
    make -j
    make install
    cd $builddir

    # build ffmpeg
    extract ffmpeg https://ffmpeg.org/releases/ffmpeg-$ffmpeg_version.tar.gz
    build ffmpeg \
        --disable-doc \
        --disable-static \
        --enable-gpl \
        --enable-libmp3lame \
        --enable-libopencore-amrnb \
        --enable-libopencore-amrwb \
        --enable-libopenjpeg \
        --enable-libopus \
        --enable-libspeex \
        --enable-libtheora \
        --enable-libtwolame \
        --enable-libvorbis \
        --enable-libx264 \
        --enable-libx265 \
        --enable-libxml2 \
        --enable-lzma \
        --enable-shared \
        --enable-version3 \
        --enable-zlib

    tar cjvf $outputfile -C $destdir include lib
fi
