#!/bin/sh

set -xe

if [ -z "$1" ]; then
    echo "Usage: $0 <prefix>"
    exit 1
fi

destdir=$1
ffmpeg_version=4.2.2

builddir=`pwd`/build
sourcedir=`pwd`/source

for d in $builddir $destdir; do
    if [ -e $d ]; then
        rm -rf $d
    fi
done

build() {
    path=$builddir/$1
    shift
    configure_args=$*
    cd $path
    ./configure $configure_args --prefix=$destdir
    make -j
    make install
    cd $builddir
}

extract() {
    path=$builddir/$1
    url=$2
    tarball=$sourcedir/`echo $url | sed -e 's/.*\///'`

    if [ -z "$3" ]; then
        strip_components=1
    else
        strip_components=$3
    fi

    if [ ! -e $tarball ]; then
        curl -L -o $tarball $url
    fi

    mkdir $path
    tar xf $tarball -C $path --strip-components $strip_components
}

cmake_args="-DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_INSTALL_PREFIX=$destdir"
if [ "`uname`" = "Linux" ]; then
    outputdir=/output
    outputfile=$outputdir/ffmpeg-$ffmpeg_version-manylinux_$(uname -m).tar.bz2
elif [ "`uname`" = "Darwin" ]; then
    outputdir=`pwd`/output
    outputfile=$outputdir/ffmpeg-$ffmpeg_version-macosx_$(uname -m).tar.bz2
    cmake_args="$cmake_args -DCMAKE_INSTALL_NAME_DIR=$destdir/lib"
else
    echo "Unknown platform"
    exit 1
fi

mkdir -p $outputdir
if [ ! -e $outputfile ]; then
    mkdir $builddir
    mkdir -p $sourcedir
    cd $builddir

    export LDFLAGS="-L$destdir/lib $LDFLAGS"
    export PATH=$destdir/bin:$PATH
    export PKG_CONFIG_PATH=$destdir/lib/pkgconfig

    #### BUILD TOOLS ####

    # needed for fontconfig
    if [ "$CIBUILDWHEEL" = "1" ] && [ "`uname`" = "Linux" ]; then
        yum -y install libuuid-devel
    fi

    # install cmake and meson
    pip install cmake meson

    # install gperf
    extract gperf http://ftp.gnu.org/pub/gnu/gperf/gperf-3.1.tar.gz
    build gperf

    # install nasm
    extract nasm https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/nasm-2.14.02.tar.bz2
    build nasm

    # install ninja
    extract ninja https://github.com/ninja-build/ninja/archive/v1.10.0.tar.gz
    cd ninja
    ./configure.py --bootstrap
    mkdir -p $destdir/bin
    cp ninja $destdir/bin
    cd $builddir

    #### LIBRARIES ###

    # build xz
    extract xz https://tukaani.org/xz/xz-5.2.5.tar.bz2
    build xz

    # build zlib
    extract zlib https://www.zlib.net/zlib-1.2.11.tar.gz
    build zlib

    # build xml2 (uses xz and zlib)
    extract xml2 ftp://xmlsoft.org/libxml2/libxml2-sources-2.9.10.tar.gz
    build xml2 --without-python

    # build freetype
    extract freetype https://download.savannah.gnu.org/releases/freetype/freetype-2.10.1.tar.gz
    build freetype

    # build fontconfig (requires freetype and libxml2)
    extract fontconfig https://www.freedesktop.org/software/fontconfig/release/fontconfig-2.13.1.tar.bz2
    build fontconfig --enable-libxml2

    # build fribidi
    extract fribidi https://github.com/fribidi/fribidi/releases/download/v1.0.9/fribidi-1.0.9.tar.xz
    build fribidi

    #### CODECS ###

    # build aom
    extract aom https://aomedia.googlesource.com/aom/+archive/a6091ebb8a7da245373e56a005f2bb95be064e03.tar.gz 0
    mkdir aom/tmp
    cd aom/tmp
    cmake .. $cmake_args -DBUILD_SHARED_LIBS=1
    make -j
    make install
    cd $builddir

    # build ass (requires freetype and fribidi)
    extract ass https://github.com/libass/libass/releases/download/0.14.0/libass-0.14.0.tar.gz
    build ass

    # build bluray (requires fontconfig)
    extract bluray https://download.videolan.org/pub/videolan/libbluray/1.1.2/libbluray-1.1.2.tar.bz2
    build bluray --disable-bdjava-jar

    # build dav1d (requires meson, nasm and ninja)
    extract dav1d https://code.videolan.org/videolan/dav1d/-/archive/master/dav1d-master.tar.bz2
    mkdir dav1d/build
    cd dav1d/build
    meson .. --libdir=lib --prefix=$destdir
    ninja
    ninja install
    cd $builddir

    # build lame
    extract lame http://deb.debian.org/debian/pool/main/l/lame/lame_3.100.orig.tar.gz
    sed -i.bak '/^lame_init_old$/d' lame/include/libmp3lame.sym
    build lame

    # build ogg
    extract ogg http://downloads.xiph.org/releases/ogg/libogg-1.3.4.tar.gz
    cat <<EOF | patch -p0
--- ogg/include/ogg/os_types.h
+++ ogg/include/ogg/os_types.h
@@ -72,11 +72,11 @@
 
 #  include <sys/types.h>
    typedef int16_t ogg_int16_t;
-   typedef uint16_t ogg_uint16_t;
+   typedef u_int16_t ogg_uint16_t;
    typedef int32_t ogg_int32_t;
-   typedef uint32_t ogg_uint32_t;
+   typedef u_int32_t ogg_uint32_t;
    typedef int64_t ogg_int64_t;
-   typedef uint64_t ogg_uint64_t;
+   typedef u_int64_t ogg_uint64_t;
 
 #elif defined(__HAIKU__)
 
EOF
    build ogg

    # build opencore-amr
    extract opencore-amr http://deb.debian.org/debian/pool/main/o/opencore-amr/opencore-amr_0.1.5.orig.tar.gz
    build opencore-amr

    # build openjpeg
    extract openjpeg https://github.com/uclouvain/openjpeg/archive/v2.3.1.tar.gz
    cd openjpeg
    cmake . $cmake_args
    make -j
    make install
    cd $builddir

    # build opus
    extract opus https://archive.mozilla.org/pub/opus/opus-1.3.1.tar.gz
    build opus

    # build speex
    extract speex http://downloads.xiph.org/releases/speex/speex-1.2.0.tar.gz
    build speex

    # build twolame
    extract twolame http://deb.debian.org/debian/pool/main/t/twolame/twolame_0.4.0.orig.tar.gz
    build twolame

    # build vorbis (requires ogg)
    extract vorbis http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.6.tar.gz
    build vorbis

    # build theora (requires vorbis)
    extract theora http://downloads.xiph.org/releases/theora/libtheora-1.1.1.tar.gz
    build theora --disable-examples

    # build wavpack
    extract wavpack http://www.wavpack.com/wavpack-5.3.0.tar.bz2
    build wavpack

    # build x264
    extract x264 https://code.videolan.org/videolan/x264/-/archive/master/x264-master.tar.bz2
    build x264 --enable-shared

    # build x265
    extract x265 http://ftp.videolan.org/pub/videolan/x265/x265_3.2.1.tar.gz
    cd x265/build
    cmake ../source $cmake_args
    make -j
    make install
    cd $builddir

    # build ffmpeg
    extract ffmpeg https://ffmpeg.org/releases/ffmpeg-$ffmpeg_version.tar.gz
    build ffmpeg \
        --disable-doc \
        --disable-static \
        --enable-fontconfig \
        --enable-gpl \
        --enable-libaom \
        --enable-libass \
        --enable-libbluray \
        --enable-libdav1d \
        --enable-libmp3lame \
        --enable-libopencore-amrnb \
        --enable-libopencore-amrwb \
        --enable-libopenjpeg \
        --enable-libopus \
        --enable-libspeex \
        --enable-libtheora \
        --enable-libtwolame \
        --enable-libvorbis \
        --enable-libwavpack \
        --enable-libx264 \
        --enable-libx265 \
        --enable-libxml2 \
        --enable-lzma \
        --enable-shared \
        --enable-version3 \
        --enable-zlib

    if [ "`uname`" = "Darwin" ]; then
        otool -L $destdir/lib/*.dylib
    fi
    tar cjvf $outputfile -C $destdir include lib
fi
