#!/bin/sh

set -e

destdir=$1
cachedir=$1.$PYTHON_ARCH

for d in ffmpeg nasm x264 $destdir; do
    if [ -e $d ]; then
        rm -rf $d
    fi
done

if [ ! -e $cachedir ]; then
    # install nasm
    if [ "`uname`" = "Linux" ]; then
        mkdir nasm
        if [ ! -e nasm.tar.bz2 ]; then
            curl -L -o nasm.tar.bz2 https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/nasm-2.14.02.tar.bz2
        fi
        tar xf nasm.tar.bz2 -C nasm --strip-components 1
        cd nasm
        ./configure --prefix=$destdir
        make -j
        make install
        cd ..

        export PATH=$destdir/bin:$PATH
    fi

    # build x264
    mkdir x264
    if [ ! -e x264.tar.bz2 ]; then
        curl -L -o x264.tar.bz2 https://code.videolan.org/videolan/x264/-/archive/master/x264-master.tar.bz2
    fi
    tar xf x264.tar.bz2 -C x264 --strip-components 1
    cd x264
    ./configure --enable-shared --prefix=$destdir
    make -j
    make install
    cd ..

    # build ffmpeg
    mkdir ffmpeg
    if [ ! -e ffmpeg.tar.gz ]; then
        curl -L -o ffmpeg.tar.gz https://ffmpeg.org/releases/ffmpeg-4.2.2.tar.gz
    fi
    tar xf ffmpeg.tar.gz -C ffmpeg --strip-components 1
    cd ffmpeg
    ./configure \
        --disable-doc \
        --disable-static \
        --enable-gpl \
        --enable-libx264 \
        --enable-shared \
        --prefix=$destdir
    make -j
    make install
    cd ..

    cp -R $destdir $cachedir
else
    cp -R $cachedir $destdir
fi
