#!/bin/bash

if [[ ! "$_PYAV_ACTIVATED" ]]; then
    export here="$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)"
    source "$here/activate.sh"
fi

cd "$PYAV_ROOT"

# Always try to install the Python dependencies they are cheap.
pip install --upgrade -r tests/requirements.txt


# Skip the rest of the build if it already exists.
if [[ -e "$PYAV_LIBRARY_PREFIX/bin/ffmpeg" ]]; then
    echo "We have a cached build of $PYAV_LIBRARY; skipping re-build."
    exit 0
fi

# Nvidia build
CONFFLAGS_NVIDIA=""
if [[ -e /usr/local/cuda ]]; then
    # Get Nvidia headers for ffmpeg
    git submodule init
    git submodule update
    cd "$PYAV_ROOT/submodules/nv-codec-headers"
    make
    sudo make install
    PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH"
    CONFFLAGS_NVIDIA="--enable-cuda \
                      --enable-cuvid \
                      --enable-nvenc \
                      --enable-nonfree \
                      --enable-libnpp \
                      --extra-cflags=-I/usr/local/cuda/include \
                      --extra-ldflags=-L/usr/local/cuda/lib64"
else
    echo "WARNING: Did not find cuda libraries in /usr/local/cuda..."
    echo "         Building without hardware acceleration support"
fi

mkdir -p "$PYAV_LIBRARY_ROOT"
mkdir -p "$PYAV_LIBRARY_PREFIX"
cd "$PYAV_LIBRARY_ROOT"

# Download and expand the source.
if [[ ! -d $PYAV_LIBRARY ]]; then
    url="https://$PYAV_LIBRARY_NAME.org/releases/$PYAV_LIBRARY.tar.gz"
    echo Downloading $url
    wget --no-check-certificate "$url" || exit 1
    tar -xzf $PYAV_LIBRARY.tar.gz
    rm $PYAV_LIBRARY.tar.gz
    echo
fi
cd $PYAV_LIBRARY

echo ./configure
if [[ "$PYAV_LIBRARY_NAME" == ffmpeg ]]; then
    CONFFLAGS=--disable-stripping
fi
./configure \
    --disable-static \
    --enable-shared \
    --disable-doc \
    --disable-optimizations \
    --disable-mmx \
    --enable-debug=3 \
    $CONFFLAGS_NVIDIA \
    $CONFFLAGS \
    --prefix="$PYAV_LIBRARY_PREFIX" \
    || exit 2
echo

echo make
make -j4 || exit 3
echo

echo make install
make install || exit 4
echo

echo Build products:
cd ~
find "$PYAV_LIBRARY_PREFIX" -name '*libav*'
