#!/bin/bash

if [[ ! "$LIBRARY" || ! "$LIBRARY_VERSION" ]]; then
    echo Please set \$LIBRARY and \$LIBRARY_VERSION
    exit 1
fi
LIBNAME=$LIBRARY-$LIBRARY_VERSION

. $HOME/venv/bin/activate
export LD_LIBRARY_PATH=$HOME/vendor/$LIBNAME/lib
export PATH=$HOME/vendor/$LIBNAME/bin:$PATH

nosetests || exit 1
