import os
import re
import sys


print '''

..
    This file is generated by includes.py; any modifications will be destroyed!

Wrapped C Types and Functions
==========================

.. warning::

    This is far from a comprehensive list, but we hope to improve it as we go.

'''

def iter_includes():
    root = os.path.abspath(os.path.join(__file__, '..', '..', 'include'))
    for dir_path, dir_names, file_names in os.walk(root):
        for file_name in file_names:
            if not file_name.endswith('.pxd'):
                continue
            yield os.path.join(dir_path, file_name)


for path in iter_includes():

    is_sphinx = False
    did_header = False

    for line in open(path):

        line = line.lstrip()
        if re.match(r'^#\s+\.\.', line):
            is_sphinx = True

        if is_sphinx and not line.startswith('#'):
            print
            is_sphinx = False

        if is_sphinx:
            if not did_header:
                print path.replace('../include/', '')
                print '-' * len(path)
                print
                did_header = True

            sys.stdout.write(re.sub(r'^# ?', '', line))
