#!/usr/bin/env bash

cd "${1-.}/_build/html"

if [[ ! -d .git ]]; then
    git init .
fi

touch .nojekyll

git add .
git commit -m "$(date)"

git push -f git@github.com:mikeboers/PyAV.git HEAD:gh-pages

